### PR TITLE
Change str concatenation to os.path.join

### PR DESCRIPTION
**Pull request by hryniuk**

### CODE REVIEW

**Comment by hryniuk** [comment]
Didn't check it on Windows :wink:.

**Comment by okraits** [comment]
I'm not convinced that using the library method here provides a real benefit, as the path is quite static here (not customizable by the user). What is the advantage in your opinion?

**Comment by hryniuk** [comment]
I'm used to using `join` and for me it's simply more obvious and "standard" way to do it. If you think it's unnecessary, this MR can be closed. There are more important things in omodoro I would like to implement :wink:.

**Comment by okraits** [comment]
Ok, convinced ;-)

**Pull request merged**
