### PR TITLE
Add option to play a simple terminal bell on status change

### PR DESCRIPTION
**Pull request by ashksmith**
I personally don't use a notification service so it was a bit hard to know the status of my cycles. I added an option to play a terminal bell when the status changes. Afaik \a should be platform independent, I've not tested it with windows.

### CODE REVIEW

**Comment by ashksmith** [comment]
The sample config file will need to be changed too.

**Comment by okraits** [comment]
I would like to ask for some improvements :)

Could you please

* squash your commits into one commit
* use a boolean value for the setting play_terminal_bell
* add that setting to the usage info
* add that setting to the end of the command line arguments
* add that setting to the sample config file and read the setting from the config file and the command line arguments at the beginning of __main__
* add that setting to README.md

Thank you in advance!

**Comment by ashksmith** [comment]
Ask and your shall receive. Let me know what you think.

**Comment by okraits** [comment]
I did some small changes and merged your changes with https://github.com/okraits/omodoro/commit/60d8b1449ec9fc2b2771dc019ff9ca927e9f59fc.
Thank you for your contribution and sorry for the delay.

**Pull request closed without merging**
